import { AdminOverviewSummary } from "./summaryTypes";

/**
 * Development-only fixture matching the schema in the delta spec.
 *
 * Production deployments should generate the summary via the operations
 * pipeline and persist it into the dataStore namespace
 * `eregisters-admin-monitoring`. The fixture lets the UI render before
 * ops has the pipeline wired up.
 */
export const FIXTURE_OVERVIEW: AdminOverviewSummary = {
    schemaVersion: "1.0.0",
    summaryType: "overview",
    period: {
        type: "THIS_YEAR",
        startDate: "2026-01-01",
        endDate: "2026-12-31",
    },
    orgUnit: {
        id: "NATIONAL",
        name: "MOH - UGANDA",
        level: "national",
        scope: "NATIONAL",
    },
    cache: {
        source: "fixture",
        generatedAt: "2026-06-28T07:00:00+03:00",
        ageSeconds: 420,
        ttlSeconds: 900,
        isStale: false,
    },
    cards: {
        facilitiesUsingERegistry: {
            key: "facilitiesUsingERegistry",
            label: "Facilities Using eRegistry",
            value: 1687,
            status: "healthy",
            source: "fixture",
        },
        registeredUsers: {
            key: "registeredUsers",
            label: "Registered Users",
            value: 15487,
            status: "healthy",
            source: "fixture",
        },
        activeUsers: {
            key: "activeUsers",
            label: "Active Users",
            value: 7997,
            status: "watch",
            source: "telemetry",
        },
        registeredClients: {
            key: "registeredClients",
            label: "Registered Clients",
            value: 666097,
            status: "healthy",
            source: "analytics",
        },
        totalEncounters: {
            key: "totalEncounters",
            label: "Total Encounters",
            value: 666198,
            status: "healthy",
            source: "analytics",
        },
        syncHealth: {
            key: "syncHealth",
            label: "Sync Health",
            value: "Watch",
            status: "watch",
            source: "access-log",
            helpText:
                "Combined score from sync volume, failed syncs, slow requests and queue status.",
        },
        systemPressure: {
            key: "systemPressure",
            label: "System Pressure",
            value: "Healthy",
            status: "healthy",
            source: "db-summary",
            helpText:
                "Hikari + Tomcat + DB connections + job backlog summaries.",
        },
        trackerGets: {
            key: "trackerGets",
            label: "Tracker GETs",
            value: 0,
            status: "healthy",
            source: "access-log",
        },
        trackerPosts: {
            key: "trackerPosts",
            label: "Tracker POSTs",
            value: 0,
            status: "healthy",
            source: "access-log",
        },
        slowRequests: {
            key: "slowRequests",
            label: "Slow Requests",
            value: 0,
            status: "healthy",
            source: "access-log",
        },
        responseVolumeMb: {
            key: "responseVolumeMb",
            label: "Tracker Response Volume",
            value: 0,
            unit: "MB",
            status: "healthy",
            source: "access-log",
        },
        unsafePatternCount: {
            key: "unsafePatternCount",
            label: "Unsafe Sync Patterns",
            value: 0,
            status: "healthy",
            source: "access-log",
        },
        appVersionStatus: {
            key: "appVersionStatus",
            label: "App Version Status",
            value: "Latest",
            status: "healthy",
            source: "telemetry",
        },
        jobBacklog: {
            key: "jobBacklog",
            label: "Tracker Job Backlog",
            value: 0,
            status: "healthy",
            source: "db-summary",
        },
        operationalAlerts: {
            key: "operationalAlerts",
            label: "Operational Alerts",
            value: 0,
            status: "healthy",
            source: "fixture",
        },
    },
    facilityRiskMap: SAMPLE_FACILITIES(),
    topFacilities: SAMPLE_FACILITIES().slice(0, 8),
    alerts: [],
    recommendations: [],
};

/**
 * Sample facility points so the dev fixture can render a representative
 * map. Coordinates are spread across Uganda's main regions. Operational
 * pipelines should overwrite these with real coordinates pulled from
 * the org-unit metadata.
 */
function SAMPLE_FACILITIES() {
    const seeds: Array<
        Omit<
            import("./summaryTypes").FacilityRiskPoint,
            "riskReasons"
        > & { riskReasons?: string[] }
    > = [
        {
            orgUnit: "ug-kla-1",
            name: "Mulago Hospital",
            districtName: "Kampala",
            regionName: "Central",
            latitude: 0.3398,
            longitude: 32.5731,
            status: "watch",
            activeUsers: 18,
            loggedInUsers: 5,
            trackerGets: 740,
            trackerPosts: 410,
            failedSyncs: 2,
            slowRequests: 14,
            responseMb: 320,
            oldAppSessions: 1,
            lastActivityAt: "2026-06-28T06:50:00+03:00",
            riskReasons: ["Tracker GET volume above threshold"],
        },
        {
            orgUnit: "ug-mb-1",
            name: "Mbale Regional Referral",
            districtName: "Mbale",
            regionName: "Eastern",
            latitude: 1.0824,
            longitude: 34.1751,
            status: "healthy",
            activeUsers: 6,
            loggedInUsers: 2,
            trackerGets: 90,
            trackerPosts: 30,
            failedSyncs: 0,
            slowRequests: 1,
            responseMb: 12,
            oldAppSessions: 0,
            lastActivityAt: "2026-06-28T06:45:00+03:00",
            riskReasons: [],
        },
        {
            orgUnit: "ug-mb-2",
            name: "Mbarara Regional Referral",
            districtName: "Mbarara",
            regionName: "Western",
            latitude: -0.6072,
            longitude: 30.6545,
            status: "healthy",
            activeUsers: 9,
            loggedInUsers: 3,
            trackerGets: 130,
            trackerPosts: 65,
            failedSyncs: 0,
            slowRequests: 0,
            responseMb: 14,
            oldAppSessions: 0,
            lastActivityAt: "2026-06-28T06:55:00+03:00",
            riskReasons: [],
        },
        {
            orgUnit: "ug-gl-1",
            name: "Gulu Regional Referral",
            districtName: "Gulu",
            regionName: "Northern",
            latitude: 2.7747,
            longitude: 32.2992,
            status: "degraded",
            activeUsers: 12,
            loggedInUsers: 4,
            trackerGets: 1200,
            trackerPosts: 980,
            failedSyncs: 5,
            slowRequests: 40,
            responseMb: 480,
            oldAppSessions: 3,
            lastActivityAt: "2026-06-28T06:30:00+03:00",
            riskReasons: [
                "Failed syncs above threshold",
                "Old app sessions still running",
            ],
        },
        {
            orgUnit: "ug-arua-1",
            name: "Arua Regional Referral",
            districtName: "Arua",
            regionName: "West Nile",
            latitude: 3.0301,
            longitude: 30.911,
            status: "healthy",
            activeUsers: 4,
            loggedInUsers: 0,
            trackerGets: 60,
            trackerPosts: 15,
            failedSyncs: 0,
            slowRequests: 0,
            responseMb: 6,
            oldAppSessions: 0,
            lastActivityAt: "2026-06-28T06:40:00+03:00",
            riskReasons: [],
        },
        {
            orgUnit: "ug-jin-1",
            name: "Jinja Regional Referral",
            districtName: "Jinja",
            regionName: "Eastern",
            latitude: 0.4316,
            longitude: 33.2042,
            status: "watch",
            activeUsers: 7,
            loggedInUsers: 2,
            trackerGets: 520,
            trackerPosts: 220,
            failedSyncs: 1,
            slowRequests: 9,
            responseMb: 180,
            oldAppSessions: 0,
            lastActivityAt: "2026-06-28T06:35:00+03:00",
            riskReasons: ["Slow requests trending up"],
        },
        {
            orgUnit: "ug-kab-1",
            name: "Kabale Regional Referral",
            districtName: "Kabale",
            regionName: "Western",
            latitude: -1.2418,
            longitude: 29.9897,
            status: "critical",
            activeUsers: 0,
            loggedInUsers: 0,
            trackerGets: 0,
            trackerPosts: 0,
            failedSyncs: 0,
            slowRequests: 0,
            responseMb: 0,
            oldAppSessions: 0,
            lastActivityAt: "2026-06-20T08:00:00+03:00",
            riskReasons: ["No activity for 8 days"],
        },
        {
            orgUnit: "ug-fp-1",
            name: "Fort Portal Regional Referral",
            districtName: "Kabarole",
            regionName: "Western",
            latitude: 0.6711,
            longitude: 30.275,
            status: "healthy",
            activeUsers: 5,
            loggedInUsers: 1,
            trackerGets: 70,
            trackerPosts: 20,
            failedSyncs: 0,
            slowRequests: 0,
            responseMb: 8,
            oldAppSessions: 0,
            lastActivityAt: "2026-06-28T06:48:00+03:00",
            riskReasons: [],
        },
    ];
    return seeds.map((s) => ({ riskReasons: s.riskReasons ?? [], ...s }));
}
